name: M10Clone

options:
  bundleIdPrefix: com.m10clone
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: ru
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: M10Clone
    PRODUCT_BUNDLE_IDENTIFIER: com.m10clone.app
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    DEVELOPMENT_TEAM: ""

targets:
  M10Clone:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: M10Clone
        name: M10Clone
        excludes:
          - "*.md"
          - "*.MD"
          - "backend"
          - "Backend"
          - ".github"
          - "Build"
          - "Info.plist"
        createIntermediateGroups: true
    info:
      path: M10Clone/Info.plist
      properties:
        CFBundleDisplayName: M10 Clone
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
    settings:
      base:
        ENABLE_PREVIEWS: "YES"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
        INFOPLIST_FILE: M10Clone/Info.plist
