name: M10Clone

options:
  bundleIdPrefix: com.m10clone
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: ru
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: M10Clone
    PRODUCT_BUNDLE_IDENTIFIER: com.m10clone.app
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    DEVELOPMENT_TEAM: ""

targets:
  M10Clone:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - M10Clone
    settings:
      base:
        INFOPLIST_FILE: M10Clone/Info.plist
        ENABLE_PREVIEWS: "YES"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
        GENERATE_INFOPLIST_FILE: "NO"
