name: M10Clone

options:
  bundleIdPrefix: com.m10clone
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: ru

settings:
  base:
    PRODUCT_NAME: M10Clone
    PRODUCT_BUNDLE_IDENTIFIER: com.m10clone.app
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1,2
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO

targets:
  M10Clone:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - M10Clone
    info:
      path: M10Clone/Info.plist
      properties:
        CFBundleDevelopmentRegion: ru
        CFBundleDisplayName: M10 Clone
        CFBundleExecutable: M10Clone
        CFBundleIdentifier: com.m10clone.app
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: M10Clone
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleSupportedPlatforms:
          - iPhoneOS
        DTPlatformName: iphoneos
        DTSDKName: iphoneos15.0
        MinimumOSVersion: "15.0"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen:
          UIColorName: AccentColor
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIDeviceFamily:
          - 1
          - 2
    settings:
      base:
        INFOPLIST_FILE: M10Clone/Info.plist
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        PROVISIONING_PROFILE_SPECIFIER: ""